version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: grades
      POSTGRES_USER: grades
      POSTGRES_PASSWORD: grades
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grades -d grades"]
      interval: 2s
      timeout: 2s
      retries: 15

  adminer:
    image: adminer:4
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
      ADMINER_DEFAULT_SERVER: db

  api:
    build: ./backend
    depends_on: [db]
    environment:
      DATABASE_URL: postgresql+psycopg://grades:grades@db:5432/grades
    ports: ["8000:8000"]
    volumes:
      - ./sample_data:/app/sample_data:ro

volumes:
  pgdata:
